// Package seed
package seed

import (
	"time"

	"github.com/adriein/hastypal/internal/business"
)

var ServiceSeed = map[string][]*business.ServiceCatalog{
	"wellness": {
	{
		ID:          1,
		Name:        "Deep Tissue Massage",
		Description: "Relieving tension with firm pressure massage.",
		Price:       80.0,
		Currency:    "USD",
		Duration:    "60min",
		BusinessID:  1,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	{
		ID:          2,
		Name:        "Hot Stone Therapy",
		Description: "Warm basalt stones to relax muscles and mind.",
		Price:       100.0,
		Currency:    "USD",
		Duration:    "75min",
		BusinessID:  1,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	{
		ID:          3,
		Name:        "Aromatherapy Facial",
		Description: "Soothing facial with essential oils.",
		Price:       65.0,
		Currency:    "USD",
		Duration:    "45min",
		BusinessID:  1,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	{
		ID:          4,
		Name:        "Sauna Session",
		Description: "Detoxifying heat therapy session.",
		Price:       30.0,
		Currency:    "USD",
		Duration:    "30min",
		BusinessID:  1,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	{
		ID:          5,
		Name:        "Reflexology",
		Description: "Foot massage targeting pressure points.",
		Price:       50.0,
		Currency:    "USD",
		Duration:    "40min",
		BusinessID:  1,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	},
	"hair": {
	{
		ID:          6,
		Name:        "Haircut & Style",
		Description: "Precision cut and finishing style.",
		Price:       40.0,
		Currency:    "USD",
		Duration:    "45min",
		BusinessID:  2,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	{
		ID:          7,
		Name:        "Coloring",
		Description: "Full color application with premium dyes.",
		Price:       90.0,
		Currency:    "USD",
		Duration:    "90min",
		BusinessID:  2,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	{
		ID:          8,
		Name:        "Balayage",
		Description: "Hand-painted highlights for a natural look.",
		Price:       120.0,
		Currency:    "USD",
		Duration:    "120min",
		BusinessID:  2,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	{
		ID:          9,
		Name:        "Keratin Treatment",
		Description: "Smoothing treatment for frizz-free hair.",
		Price:       150.0,
		Currency:    "USD",
		Duration:    "150min",
		BusinessID:  2,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
{
		ID:          10,
		Name:        "Beard Trim",
		Description: "Shaping and conditioning for the beard.",
		Price:       25.0,
		Currency:    "USD",
		Duration:    "20min",
		BusinessID:  2,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	},
	"hospitality": {
{
		ID:          11,
		Name:        "Standard Room - Night",
		Description: "Comfortable one-night stay.",
		Price:       120.0,
		Currency:    "USD",
		Duration:    "1 night",
		BusinessID:  3,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
{
		ID:          12,
		Name:        "Deluxe Suite - Night",
		Description: "Spacious suite with city view.",
		Price:       250.0,
		Currency:    "USD",
		Duration:    "1 night",
		BusinessID:  3,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
{
		ID:          13,
		Name:        "Airport Transfer",
		Description: "Private pickup and drop-off.",
		Price:       45.0,
		Currency:    "USD",
		Duration:    "45min",
		BusinessID:  3,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
{
		ID:          14,
		Name:        "Spa Breakfast",
		Description: "Full buffet breakfast for two.",
		Price:       35.0,
		Currency:    "USD",
		Duration:    "1.5hrs",
		BusinessID:  3,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
{
		ID:          15,
		Name:        "Late Checkout",
		Description: "Extended stay until evening.",
		Price:       40.0,
		Currency:    "USD",
		Duration:    "6hrs",
		BusinessID:  3,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	},
	"restaurant": {
{
		ID:          16,
		Name:        "Chef's Tasting Menu",
		Description: "Multi-course culinary experience.",
		Price:       85.0,
		Currency:    "USD",
		Duration:    "2.5hrs",
		BusinessID:  4,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
{
		ID:          17,
		Name:        "Weekend Brunch",
		Description: "Bottomless brunch special.",
		Price:       45.0,
		Currency:    "USD",
		Duration:    "2hrs",
		BusinessID:  4,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
{
		ID:          18,
		Name:        "Wine Pairing Dinner",
		Description: "Dinner with curated wine selections.",
		Price:       110.0,
		Currency:    "USD",
		Duration:    "3hrs",
		BusinessID:  4,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
{
		ID:          19,
		Name:        "Private Chef Service",
		Description: "In-home chef for special events.",
		Price:       300.0,
		Currency:    "USD",
		Duration:    "4hrs",
		BusinessID:  4,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
{
		ID:          20,
		Name:        "Cooking Class",
		Description: "Hands-on class with head chef.",
		Price:       70.0,
		Currency:    "USD",
		Duration:    "2hrs",
		BusinessID:  4,
		DateAdd:     time.Now(),
		DateUpd:     time.Now(),
	},
	},
}

var BusinessSeed = []*business.Business{
	{
		ID:             1,
		Name:           "Serenity Wellness Spa",
		ContactPhone:   "+1 555 0101",
		Email:          "contact@serenityspa.com",
		Address:        "12 Relaxation Ave",
		Country:        "USA",
		Lang:           "en",
		ServiceCatalog: ServiceSeed["wellness"],
		DateAdd:        time.Now(),
		DateUpd:        time.Now(),
	},
	{
		ID:             2,
		Name:           "Glam Hair Studio",
		ContactPhone:   "+1 555 0102",
		Email:          "hello@glamhair.com",
		Address:        "45 Style Blvd",
		Country:        "USA",
		Lang:           "en",
		ServiceCatalog: ServiceSeed["hair"],
		DateAdd:        time.Now(),
		DateUpd:        time.Now(),
	},
	{
		ID:             3,
		Name:           "Grand Heritage Hotel",
		ContactPhone:   "+1 555 0103",
		Email:          "reservations@grandheritage.com",
		Address:        "1 King Street",
		Country:        "USA",
		Lang:           "en",
		ServiceCatalog: ServiceSeed["hospitality"],
		DateAdd:        time.Now(),
		DateUpd:        time.Now(),
	},
	{
		ID:             4,
		Name:           "Savor & Flame Restaurant",
		ContactPhone:   "+1 555 0104",
		Email:          "bookings@savorflame.com",
		Address:        "78 Gourmet Lane",
		Country:        "USA",
		Lang:           "en",
		ServiceCatalog: ServiceSeed["restaurant"],
		DateAdd:        time.Now(),
		DateUpd:        time.Now(),
	},
}
